# Generated by Django 4.2.7 on 2023-11-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osanka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_from',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
