# Generated by Django 4.2.7 on 2023-12-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osanka', '0002_alter_users_date_from_alter_users_date_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(auto_now=True)),
                ('date_to', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_to',
        ),
        migrations.CreateModel(
            name='Wrong_pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osanka.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='Users_achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.IntegerField(verbose_name='Achievements')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osanka.users')),
            ],
        ),
        migrations.AddField(
            model_name='sessions',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osanka.users'),
        ),
    ]
